import { floorPercent } from '../../src/core/money.js'
import type { DeedState, GameState, PoolAssetRef, SwapReference } from '../../src/core/state.js'
import type { BriberyEffect } from '../../src/core/events.js'
import type { ContractId, DeedId, Money, PlayerId } from '../../src/core/types.js'
import type { Rejection } from '../../src/core/errors.js'
import type { GameEvent } from '../../src/core/events.js'
import { decideCreditAction, decidePropertyAction } from '../../src/core/decide.js'
import { HOTEL_LEVEL, canBuildOn, isBuildable, ownsWholeGroup } from '../../src/contexts/board/index.js'
import { decideMarkets } from '../../src/contexts/markets/index.js'
import { decideSecuritization, expectedPoolCashflow } from '../../src/contexts/securitization/index.js'
import { decideUnderworld } from '../../src/contexts/underworld/index.js'
import { ECONOMY } from '../../src/config/economy.js'
import type { Percent, ScriptedAction, Slot } from './arbitraries.js'

export function at<T>(items: readonly T[], index: Slot): T | null {
  if (items.length === 0) return null
  return items[Math.abs(index) % items.length] ?? null
}

export function actorAt(state: GameState, index: Slot): PlayerId {
  return at(state.config.turnOrder, index) ?? 'P1'
}

/** A player who is not `self`, so SELF_DEALING is never generated by accident. */
export function otherThan(state: GameState, self: PlayerId, index: Slot): PlayerId | null {
  const others = state.config.turnOrder.filter((p) => p !== self)
  return at(others, index)
}

/** Narrows `DeedState.owner` (`PlayerId | 'bank' | null`) to an actual player. Every
 * deed not yet drafted, or that never gets drafted (`unlockMode` and the 7-round draft
 * budget do not guarantee all 28 are claimed), reads `owner: null`; a few are `'bank'`.
 * `build-house`/`sell-house` below scan ALL deeds on the board (not just one actor's),
 * so — unlike `deedsOf`, which is already scoped to one player's holdings and therefore
 * never needs this — they must filter these out before treating `.owner` as a `PlayerId`
 * (`tests/` is outside `tsconfig.json`'s `include`, so `npm run typecheck` does not
 * catch a mistake here; this repo's test files carry that discipline manually). */
function isPlayerOwned(deed: DeedState): deed is DeedState & { owner: PlayerId } {
  return deed.owner !== null && deed.owner !== 'bank'
}

export function amount(balance: Money, pct: Percent): Money {
  return floorPercent(Math.max(0, balance), pct / 100)
}

/** Owned, unmortgaged deeds — the shape most actions need (build, mortgage, futures,
 * options, trade-outs). Deliberately excludes mortgaged deeds; `mortgagedDeedsOf`
 * below is the complement, for the one action that needs the opposite filter. */
export function deedsOf(state: GameState, player: PlayerId): readonly DeedId[] {
  return Object.values(state.deeds)
    .filter((d) => d.owner === player && !d.mortgaged)
    .map((d) => d.id)
}

/** Owned, MORTGAGED deeds — the only pool `unmortgage-deed` may legally draw from. */
export function mortgagedDeedsOf(state: GameState, player: PlayerId): readonly DeedId[] {
  return Object.values(state.deeds)
    .filter((d) => d.owner === player && d.mortgaged)
    .map((d) => d.id)
}

export function loansOf(state: GameState, player: PlayerId, side: 'lender' | 'borrower'):
readonly ContractId[] {
  return state.loans
    .filter((l) => l.status === 'active' && l[side] === player)
    .map((l) => l.id)
}

export function futuresOf(state: GameState, player: PlayerId): readonly ContractId[] {
  return state.futures.filter((f) => f.holder === player).map((f) => f.id)
}

export function optionsOf(state: GameState, player: PlayerId): readonly ContractId[] {
  return state.options.filter((o) => o.holder === player).map((o) => o.id)
}

/**
 * Assets the player can legitimately pool: loans they lent, futures and options they
 * hold. `create-pool` needs three, which is why the arm carries no asset slots — picking
 * three at random from a list of three or four is pure rejection, so the driver takes the
 * first three instead and lets the count guard do the rejecting.
 */
export function poolableAssets(state: GameState, player: PlayerId): readonly PoolAssetRef[] {
  return [
    ...loansOf(state, player, 'lender').map((id): PoolAssetRef => ({ kind: 'peer-loan', id })),
    ...futuresOf(state, player).map((id): PoolAssetRef => ({ kind: 'rent-future', id })),
    ...optionsOf(state, player).map((id): PoolAssetRef => ({ kind: 'deed-option', id })),
  ]
}

/** Every obligation a swap can reference: active peer loans and live tranches. */
export function swapReferences(state: GameState): readonly SwapReference[] {
  return [
    ...state.loans
      .filter((l) => l.status === 'active')
      .map((l): SwapReference => ({ kind: 'peer-loan', id: l.id })),
    ...state.pools
      .filter((p) => !p.terminated)
      .flatMap((p) => p.tranches.map((t): SwapReference =>
        ({ kind: 'tranche', poolId: p.id, tranche: t.kind }))),
  ]
}

export function briberyEffect(
  state: GameState, self: PlayerId, which: 0 | 1 | 2, target: Slot,
): BriberyEffect | null {
  if (which === 1) return { kind: 'cancel-card' }
  if (which === 2) return { kind: 'delay-margin-call' }
  const victim = otherThan(state, self, target)
  return victim === null ? null : { kind: 'force-reroll', target: victim }
}

/** Contract ids are derived, never generated — the engine holds no Math.random. */
export function scriptedId(prefix: string, state: GameState, actor: PlayerId, n: number): ContractId {
  return `${prefix}-${actor}-r${state.round}-${n}`
}

export type Outcome = readonly GameEvent[] | Rejection | null

/**
 * One arm, one decider call, dispatched through `core/decide.ts`'s real port wiring
 * (`decidePropertyAction`/`decideCreditAction`) rather than a context's own `NO_*`
 * default — the same wiring the facilitator uses, so a generated liquidation actually
 * makes an encumbrance holder whole instead of silently zeroing the make-whole amount.
 * `null` means "this action had no legal target in this state", which the driver counts
 * as SKIPPED rather than REJECTED: a skip means the generator produced nothing for the
 * engine to judge, while a rejection means the engine judged and refused.
 */
export function dispatch(state: GameState, action: ScriptedAction, seq: number): Outcome {
  const self = actorAt(state, action.actor)
  const me = state.players[self]

  switch (action.kind) {
    case 'draw-credit':
      return decideCreditAction(state,
        { type: 'DrawCredit', player: self, amount: amount(2_000, action.percent) })

    case 'repay-credit':
      return decideCreditAction(state,
        { type: 'RepayCredit', player: self, amount: amount(me.drawnCredit, action.percent) })

    case 'repay-distressed': {
      // Same "derive the actor from whoever can legally do this" pattern as
      // `build-house`/`sell-house`/`sell-tranche` above, and for the identical reason:
      // `distressedDebt` is nonzero for at most one or two of the four players even in
      // `arbDistressGameScript`'s engineered histories, so requiring `self` (a
      // uniformly random actor slot) to coincide with that specific player wasted three
      // out of four attempts on `command.amount === 0` -> INVALID_AMOUNT. Measured at
      // 0.40% acceptance with the coincidence still in place, just under this suite's
      // 0.5% floor — see the task report.
      const indebted = state.config.turnOrder.filter((p) => state.players[p].distressedDebt > 0)
      const debtor = at(indebted, action.actor)
      if (debtor === null) return null
      const d = state.players[debtor]
      return decideCreditAction(state, {
        type: 'RepayDistressedDebt', player: debtor,
        amount: amount(d.distressedDebt, action.percent),
      })
    }

    case 'originate-peer-loan': {
      const borrower = otherThan(state, self, action.counterparty)
      const pledge = borrower === null ? null : at(deedsOf(state, borrower), action.collateral)
      if (borrower === null || pledge === null) return null
      return decideCreditAction(state, {
        type: 'OriginatePeerLoan', lender: self, borrower,
        principal: amount(me.cleanCash, action.percent),
        ratePerRound: action.ratePerRound,
        termRounds: action.termRounds,
        collateral: [pledge],
      })
    }

    case 'repay-peer-loan': {
      const id = at(loansOf(state, self, 'borrower'), action.contract)
      const loan = id === null ? undefined : state.loans.find((l) => l.id === id)
      if (id === null || loan === undefined) return null
      return decideCreditAction(state,
        { type: 'RepayPeerLoan', player: self, id, amount: amount(loan.outstanding, action.percent) })
    }

    case 'sell-peer-loan': {
      const id = at(loansOf(state, self, 'lender'), action.contract)
      const to = otherThan(state, self, action.counterparty)
      const loan = id === null ? undefined : state.loans.find((l) => l.id === id)
      if (id === null || to === null || loan === undefined) return null
      return decideCreditAction(state,
        { type: 'SellPeerLoanNote', player: self, id, to, price: amount(loan.outstanding, action.percent) })
    }

    case 'originate-future': {
      const deed = at(deedsOf(state, self), action.deed)
      const holder = otherThan(state, self, action.counterparty)
      if (deed === null || holder === null) return null
      // `window` is the contract LENGTH in rounds, capped at MAX_FUTURE_WINDOW: the
      // decider computes length as endRound - startRound + 1, and startRound must
      // exceed the current round, so an off-by-one here would make every future
      // one round longer than intended and reject at exactly the cap.
      const length = Math.max(1, Math.min(action.window, ECONOMY.MAX_FUTURE_WINDOW))
      const startRound = state.round + 1
      return decideMarkets(state, {
        type: 'OriginateRentFuture', player: self, deed, holder,
        startRound, endRound: startRound + length - 1,
        price: amount(state.deeds[deed]?.faceValue ?? 0, action.percent),
      })
    }

    case 'sell-future': {
      const contract = at(futuresOf(state, self), action.contract)
      const to = otherThan(state, self, action.counterparty)
      if (contract === null || to === null) return null
      return decideMarkets(state, {
        type: 'SellRentFuture', player: self, contract, to,
        price: amount(me.cleanCash, action.percent),
      })
    }

    case 'write-option': {
      const deed = at(deedsOf(state, self), action.deed)
      const holder = otherThan(state, self, action.counterparty)
      if (deed === null || holder === null) return null
      const face = state.deeds[deed]?.faceValue ?? 0
      return decideMarkets(state, {
        type: 'WriteDeedOption', player: self, deed, holder,
        premium: amount(face, action.premiumPercent),
        strike: amount(face, action.strikePercent),
        expiry: state.round + action.window,
      })
    }

    case 'sell-option': {
      const contract = at(optionsOf(state, self), action.contract)
      const to = otherThan(state, self, action.counterparty)
      if (contract === null || to === null) return null
      return decideMarkets(state, {
        type: 'SellDeedOption', player: self, contract, to,
        price: amount(me.cleanCash, action.percent),
      })
    }

    case 'exercise-option': {
      const contract = at(optionsOf(state, self), action.contract)
      if (contract === null) return null
      return decideMarkets(state, { type: 'ExerciseDeedOption', player: self, contract })
    }

    case 'create-pool': {
      const assets = poolableAssets(state, self).slice(0, 3)
      if (assets.length < 3) return null
      const poolId = scriptedId('pool', state, self, seq)
      const cashflow = expectedPoolCashflow(state, {
        id: poolId, originator: self, assets, tranches: [], terminated: false,
      })
      return decideSecuritization(state, {
        type: 'CreatePool', player: self, poolId, assets,
        seniorFace: amount(cashflow, action.seniorPercent),
        mezzanineFace: amount(cashflow, action.mezzaninePercent),
      })
    }

    case 'sell-tranche': {
      // Resolves the seller from the tranche's ACTUAL holder, not from `action.actor`:
      // `SellTranche` rejects NOT_OWNER unless `player` already holds the named tranche,
      // and the pool creator (whoever holds the freshly minted tranches) is essentially
      // never the same slot a uniformly random `action.actor` happens to name — measured
      // at 0.2% acceptance against `create-pool` firing at all (~1.3%), i.e. most
      // `sell-tranche` attempts against a live pool were failing on actor coincidence
      // alone, not on any real precondition. See the task report for both figures.
      const pool = at(state.pools.filter((p) => !p.terminated), action.pool)
      const tranche = pool === null ? null : at(pool.tranches, action.tranche)
      if (pool === null || tranche === null) return null
      const to = otherThan(state, tranche.holder, action.counterparty)
      if (to === null) return null
      return decideSecuritization(state, {
        type: 'SellTranche', player: tranche.holder, poolId: pool.id, tranche: tranche.kind, to,
        price: amount(tranche.face, action.percent),
      })
    }

    case 'write-swap': {
      const reference = at(swapReferences(state), action.reference)
      const buyer = otherThan(state, self, action.counterparty)
      if (reference === null || buyer === null) return null
      const notional = amount(1_000, action.notionalPercent)
      return decideSecuritization(state, {
        type: 'WriteSwap', swapId: scriptedId('swap', state, self, seq),
        buyer, seller: self, reference, notional,
        premiumPerRound: amount(notional, action.premiumPercent),
      })
    }

    case 'launch-venture':
      return decideUnderworld(state, {
        type: 'LaunchVenture', player: self,
        venture: action.venture, fundedFrom: action.fundedFrom,
      })

    case 'speakeasy':
      return decideUnderworld(state, {
        type: 'PlaySpeakeasy', player: self, dice: action.dice, fundedFrom: action.fundedFrom,
      })

    case 'launder':
      return decideUnderworld(state,
        { type: 'LaunderCash', player: self, amount: amount(me.dirtyCash, action.percent) })

    case 'bribe': {
      const effect = briberyEffect(state, self, action.effect, action.target)
      return effect === null ? null : decideUnderworld(state, { type: 'Bribe', player: self, effect })
    }

    case 'insider-trade':
      return decideUnderworld(state,
        { type: 'InsiderTrade', player: self, fundedFrom: action.fundedFrom })

    case 'build-house': {
      // Resolves the builder from ANY deed on the board that is structurally eligible
      // to build on right now (whole unmortgaged colour group owned by one player, not
      // already a hotel, satisfies the even-build rule), rather than requiring `self`
      // (a uniformly random actor slot) to happen to be that player. Owning a complete
      // colour group is already rare — measured well under 0.5% acceptance when legality
      // additionally required actor coincidence; see `sell-tranche` above for the same
      // pattern applied to a pool. `decidePropertyAction` still re-checks everything
      // (including affordability) and can still reject, e.g. on insufficient headroom.
      const candidates = Object.values(state.deeds)
        .filter(isPlayerOwned)
        .filter((d) => isBuildable(d) && !d.mortgaged && d.houses < HOTEL_LEVEL
          && ownsWholeGroup(state, d.group, d.owner) && canBuildOn(state, d))
      const target = at(candidates, action.deed)
      if (target === null) return null
      return decidePropertyAction(state, { type: 'BuildHouse', player: target.owner, deed: target.id })
    }

    case 'sell-house': {
      // Same idea as `build-house` just above: pick from any deed on the board that
      // currently carries a house, whoever owns it, instead of requiring `self` to be
      // that owner. `decidePropertyAction` still re-checks the even-build rule and the
      // hotel-breaking house-supply guard. `houses > 0` alone already implies a real
      // owner (an undrafted or bank-held deed can never have been built on), but the
      // guard is applied anyway so `target.owner` narrows to `PlayerId` without a cast.
      const candidates = Object.values(state.deeds).filter(isPlayerOwned).filter((d) => d.houses > 0)
      const target = at(candidates, action.deed)
      if (target === null) return null
      return decidePropertyAction(state, { type: 'SellHouse', player: target.owner, deed: target.id })
    }

    case 'mortgage-deed': {
      const deed = at(deedsOf(state, self), action.deed)
      if (deed === null) return null
      return decidePropertyAction(state, { type: 'MortgageDeed', player: self, deed })
    }

    case 'unmortgage-deed': {
      const deed = at(mortgagedDeedsOf(state, self), action.deed)
      if (deed === null) return null
      return decidePropertyAction(state, { type: 'UnmortgageDeed', player: self, deed })
    }

    case 'trade-deeds': {
      const to = otherThan(state, self, action.counterparty)
      if (to === null) return null
      const give = at(deedsOf(state, self), action.deedFrom)
      const take = at(deedsOf(state, to), action.deedTo)
      const deedsFrom = give === null ? [] : [give]
      const deedsTo = take === null ? [] : [take]
      return decidePropertyAction(state, {
        type: 'TradeAssets', from: self, to,
        deedsFrom, deedsTo,
        cashFrom: amount(me.cleanCash, action.cashFromPercent),
        cashTo: amount(state.players[to].cleanCash, action.cashToPercent),
        confirmedBy: [self, to],
      })
    }
  }
}
